import Head from "next/head";
import { useContext, useState } from "react";
import UploadImage from "../components/UploadImage";
import Uploading from "../components/Uploading";
import uiContext from "../store/ui-context";
import styles from "../styles/Home.module.css";

export default function Home() {
  const ctx = useContext(uiContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devchallenges.png" />
      </Head>

      <div className={styles.container}>
        <UploadImage />

        <div className="footer__owner">
          created by <a href="https://github.com/bashidagha">bashidagha</a> -
          devChallenges.io
        </div>
      </div>
    </>
  );
}
